---
version: "3"
dotenv:
  - .env
tasks:
  validate:
    silent: true
    cmds:
      - resumed validate
  theme:build:
    silent: true
    dir: theme
    cmds:
      - npm run build
  build:
    silent: true
    desc: Build resume
    cmds:
      - |
        rm -rf build
        mkdir build
        cat resume.json | \
          jq \
            '.basics.email="{{.EMAIL}}"|.basics.phone="{{.PHONE}}"' \
            resume.json \
          > build/resume.json
        resumed render build/resume.json --output build/resume.html
        weasyprint build/resume.html build/resume.pdf
